In [30]:
# Librerías
import pandas as pd
import requests
import sqlite3
import openpyxl

In [3]:
# Data Educacion
api_url_educacion = "https://www.datos.gov.co/resource/nudc-7mev.json?$limit=50000"


try:
    response_edu = requests.get(api_url_educacion)
    response_edu.raise_for_status()  # Lanza un error si la petición falla (ej: 404)
    data_edu = response_edu.json()
    df_raw_edu = pd.DataFrame(data_edu)
    print(f"✅ ¡Extracción exitosa! Se cargaron {len(df_raw_edu)} filas.")
    display(df_raw_edu.head())

except requests.exceptions.RequestException as e_edu:
    print(f"❌ Error al extraer los datos: {e_edu}")
    df_raw_edu = pd.DataFrame() # Creamos un dataframe vacío para evitar errores posteriores

except Exception as e_edu:
    print(f"❌ Ocurrió un error inesperado: {e_edu}")
    df_raw_edu = pd.DataFrame()

✅ ¡Extracción exitosa! Se cargaron 14585 filas.

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaquí,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mitú,97,Vaupés,3831,Vaupés (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaupés,3831,Vaupés (ETC),1228,51.3,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN

In [ ]:
# Listado años
años = (df_raw_edu["a_o"]           
           .dropna()                 
           .astype(int)              
           .sort_values()            
           .unique())                
print("Años disponibles:", años)

Años disponibles: [2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023]

In [5]:
df_raw2 = df_raw_edu.copy()

In [6]:
df_raw.shape

(14585, 41)

In [7]:
df_raw2['new_index'] = range(1,df_raw.shape[0]+1)

In [8]:
df_raw2.set_index('new_index',inplace=True)

In [9]:
df_raw2.head()

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
new_index,,,,,,,,,,,,,,,,,,,,,
1,2023,05004,Abriaquí,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
2,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
3,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
4,2023,97001,Mitú,97,Vaupés,3831,Vaupés (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
5,2023,97161,Caruru,97,Vaupés,3831,Vaupés (ETC),1228,51.3,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN

In [10]:
df_raw.drop_duplicates().shape

(14585, 41)

## Limpieza de datos

In [11]:
df_raw['tasa_matriculaci_n_5_16'] = df_raw['tasa_matriculaci_n_5_16'].astype(float)

In [12]:
df_raw.groupby(['c_digo_departamento','departamento'])['tasa_matriculaci_n_5_16'].mean().reset_index()

,c_digo_departamento,departamento,tasa_matriculaci_n_5_16
0,0,NACIONAL,0.922600
1,05,Antioquia,84.215040
2,08,Atlántico,83.640435
3,11,Bogotá D.C.,96.410000
4,11,"Bogotá, D.C.",86.860833
5,13,Bolívar,86.463798
6,15,Boyacá,82.983827
7,17,Caldas,82.187436
8,18,Caquetá,75.105529
9,19,Cauca,79.346987
10,20,Cesar,96.113944
11,23,Córdoba,88.003057
12,25,Cundinamarca,87.205280
13,27,Chocó,80.573439
14,41,Huila,85.088420
15,44,La Guajira,80.790923
16,47,Magdalena,94.591410
17,5,Antioquia,88.194655
18,50,Meta,91.258147
19,52,Nariño,75.909501
20,54,Norte de Santander,83.849499
21,63,Quindio,93.880000
22,66,Risaralda,84.438242
23,68,Santander,87.187691
24,70,Sucre,95.251538
25,73,Tolima,87.923552
26,76,Valle del Cauca,84.256264
27,8,Atlántico,89.949373
28,81,Arauca,79.976484
29,85,Casanare,89.254321
30,86,Putumayo,79.806647
31,88,"Archipiélago de San Andrés, Providencia y Sant...",80.197083
32,88,Archipiélago de San Andrés. Providencia y Sant...,84.980000
33,91,Amazonas,57.911240
34,94,Guainía,60.224216
35,95,Guaviare,56.902692
36,97,Vaupés,60.409855
37,99,Vichada,79.675769

In [13]:
df_raw[df_raw['departamento']!= 'NACIONAL']

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaquí,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mitú,97,Vaupés,3831,Vaupés (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaupés,3831,Vaupés (ETC),1228,51.30,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14580,2011,5036,Angelópolis,5,Antioquia,3758,Antioquia (ETC),1707,78.85,78.9,...,3.61,9.5,7.32,0.71,0,0.7,1.08,0,19.57,100
14581,2011,5034,Andes,5,Antioquia,3758,Antioquia (ETC),10244,84.45,84.5,...,0.58,0.04,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44
14582,2011,5031,Amalfi,5,Antioquia,3758,Antioquia (ETC),5552,97.71,97.7,...,0,0,0,NaN,0.83,NaN,9.93,4.47,20.01,53.45
14583,2011,5030,Amagá,5,Antioquia,3758,Antioquia (ETC),6631,78.65,78.7,...,6.73,14.46,7.45,0.42,0,0.24,0.91,0,25.05,83.33
14584,2011,5021,Alejandría,5,Antioquia,3758,Antioquia (ETC),702,118.52,118.5,...,2.16,4.39,8.04,0.6,0,0.96,0,0,32.14,81.25

In [14]:
df_raw.query("departamento != 'NACIONAL'")

,a_o,c_digo_municipio,municipio,c_digo_departamento,departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,...,reprobaci_n_primaria,reprobaci_n_secundaria,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet
0,2023,05004,Abriaquí,05,Antioquia,3758,Antioquia (ETC),503,62.62,62.62,...,1.96,16.51,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN
1,2023,95025,El Retorno,95,Guaviare,3830,Guaviare (ETC),4438,53.27,53.27,...,7.11,9.39,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN
2,2023,95200,Miraflores,95,Guaviare,3830,Guaviare (ETC),2014,32.52,32.52,...,6.93,14.13,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN
3,2023,97001,Mitú,97,Vaupés,3831,Vaupés (ETC),10986,59.57,59.57,...,4.04,8.33,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN
4,2023,97161,Caruru,97,Vaupés,3831,Vaupés (ETC),1228,51.30,51.3,...,7.32,15.28,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14580,2011,5036,Angelópolis,5,Antioquia,3758,Antioquia (ETC),1707,78.85,78.9,...,3.61,9.5,7.32,0.71,0,0.7,1.08,0,19.57,100
14581,2011,5034,Andes,5,Antioquia,3758,Antioquia (ETC),10244,84.45,84.5,...,0.58,0.04,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44
14582,2011,5031,Amalfi,5,Antioquia,3758,Antioquia (ETC),5552,97.71,97.7,...,0,0,0,NaN,0.83,NaN,9.93,4.47,20.01,53.45
14583,2011,5030,Amagá,5,Antioquia,3758,Antioquia (ETC),6631,78.65,78.7,...,6.73,14.46,7.45,0.42,0,0.24,0.91,0,25.05,83.33
14584,2011,5021,Alejandría,5,Antioquia,3758,Antioquia (ETC),702,118.52,118.5,...,2.16,4.39,8.04,0.6,0,0.96,0,0,32.14,81.25

In [15]:
resumen_matriculados_v0=(
    df_raw
    .query("departamento != 'NACIONAL'")
    .groupby(['c_digo_departamento','departamento'])
    ['tasa_matriculaci_n_5_16']
    .mean()
    .reset_index()
)

In [16]:
def ajuste_cod_depto(codigo):
    if len(codigo)==1:
        codigo = '0' + codigo
    return codigo

In [17]:
df_raw['c_digo_departamento'] = df_raw['c_digo_departamento'].apply(ajuste_cod_depto)

In [18]:
(
    df_raw
    .query("departamento != 'NACIONAL'")
    .groupby(['c_digo_departamento','departamento'])
    ['tasa_matriculaci_n_5_16']
    .mean()
    .reset_index()
)

,c_digo_departamento,departamento,tasa_matriculaci_n_5_16
0,05,Antioquia,87.887206
1,08,Atlántico,89.455816
2,11,Bogotá D.C.,96.410000
3,11,"Bogotá, D.C.",86.860833
4,13,Bolívar,86.463798
5,15,Boyacá,82.983827
6,17,Caldas,82.187436
7,18,Caquetá,75.105529
8,19,Cauca,79.346987
9,20,Cesar,96.113944
10,23,Córdoba,88.003057
11,25,Cundinamarca,87.205280
12,27,Chocó,80.573439
13,41,Huila,85.088420
14,44,La Guajira,80.790923
15,47,Magdalena,94.591410
16,50,Meta,91.258147
17,52,Nariño,75.909501
18,54,Norte de Santander,83.849499
19,63,Quindio,93.880000
20,66,Risaralda,84.438242
21,68,Santander,87.187691
22,70,Sucre,95.251538
23,73,Tolima,87.923552
24,76,Valle del Cauca,84.256264
25,81,Arauca,79.976484
26,85,Casanare,89.254321
27,86,Putumayo,79.806647
28,88,"Archipiélago de San Andrés, Providencia y Sant...",80.197083
29,88,Archipiélago de San Andrés. Providencia y Sant...,84.980000
30,91,Amazonas,57.911240
31,94,Guainía,60.224216
32,95,Guaviare,56.902692
33,97,Vaupés,60.409855
34,99,Vichada,79.675769

In [19]:
tabla_deptos = (
    df_raw
    .query("departamento != 'NACIONAL'")
    [['c_digo_departamento','departamento']]
    .drop_duplicates()
    .groupby('c_digo_departamento')
    .sample(n=1, random_state=1)
    .reset_index()
    .drop(columns= 'index')
)

In [20]:
df_raw = (
    df_raw
    .query("departamento != 'NACIONAL'")
    .drop(columns = 'departamento')
    .merge(tabla_deptos, on = 'c_digo_departamento', how = 'left')
)

In [21]:
(
    df_raw
    .query("departamento != 'NACIONAL'")
    .groupby(['c_digo_departamento','departamento'])
    ['tasa_matriculaci_n_5_16']
    .mean()
    .reset_index()
)

,c_digo_departamento,departamento,tasa_matriculaci_n_5_16
0,05,Antioquia,87.887206
1,08,Atlántico,89.455816
2,11,"Bogotá, D.C.",87.595385
3,13,Bolívar,86.463798
4,15,Boyacá,82.983827
5,17,Caldas,82.187436
6,18,Caquetá,75.105529
7,19,Cauca,79.346987
8,20,Cesar,96.113944
9,23,Córdoba,88.003057
10,25,Cundinamarca,87.205280
11,27,Chocó,80.573439
12,41,Huila,85.088420
13,44,La Guajira,80.790923
14,47,Magdalena,94.591410
15,50,Meta,91.258147
16,52,Nariño,75.909501
17,54,Norte de Santander,83.849499
18,63,Quindio,93.880000
19,66,Risaralda,84.438242
20,68,Santander,87.187691
21,70,Sucre,95.251538
22,73,Tolima,87.923552
23,76,Valle del Cauca,84.256264
24,81,Arauca,79.976484
25,85,Casanare,89.254321
26,86,Putumayo,79.806647
27,88,"Archipiélago de San Andrés, Providencia y Sant...",80.565000
28,91,Amazonas,57.911240
29,94,Guainía,60.224216
30,95,Guaviare,56.902692
31,97,Vaupés,60.409855
32,99,Vichada,79.675769

In [22]:
def longitud_cod_mpio(codigo):
    return len(codigo)

set(
    df_raw
    .query("departamento != 'NACIONAL'")
    .assign(len_codigo_mpio = lambda x: x['c_digo_municipio'].apply(longitud_cod_mpio)) 
    ['len_codigo_mpio']
    .astype(str)
)

{'4', '5'}

In [23]:
def ajuste_cod_mpio(codigo):
    if len(codigo)==4:
        codigo = '0' + codigo
    return codigo

In [24]:
df_raw['c_digo_municipio'] = df_raw['c_digo_municipio'].apply(ajuste_cod_mpio)

## Bodega de datos

In [25]:
conn = sqlite3.connect("Datos2.db")
cursor = conn.cursor()

In [31]:
datos_2005_2019 = pd.read_excel("..\Datos\Proyecciones_2005_2019.xlsx")
datos_2020_2035 = pd.read_excel("..\Datos\Proyecciones_2020_2035.xlsx")

In [32]:
datos_2005_2019.to_sql("informacion_antes_pandemia",conn)
datos_2020_2035.to_sql("informacion_despues_pandemia",conn)

53856

In [33]:
consulta = """
CREATE TABLE info_proyeccion_mpios
AS

SELECT 
CASE WHEN LENGTH(CAST(DP AS STRING)) = 1 THEN CONCAT('0',CAST(DP AS STRING))
ELSE CAST(DP AS STRING) END AS c_digo_departamento,
CASE WHEN LENGTH(CAST(MPIO AS STRING)) = 4 THEN CONCAT('0',CAST(MPIO AS STRING))
ELSE CAST(MPIO AS STRING) END AS c_digo_municipio,
AÑO AS a_o,
Población AS poblacion_total
FROM informacion_antes_pandemia
WHERE `ÁREA GEOGRÁFICA` = 'Total'

UNION ALL

SELECT 
CASE WHEN LENGTH(CAST(DP AS STRING)) = 1 THEN CONCAT('0',CAST(DP AS STRING))
ELSE CAST(DP AS STRING) END AS c_digo_departamento,
CASE WHEN LENGTH(CAST(MPIO AS STRING)) = 4 THEN CONCAT('0',CAST(MPIO AS STRING))
ELSE CAST(MPIO AS STRING) END AS c_digo_municipio,
AÑO AS a_o,
Población AS poblacion_total
FROM informacion_despues_pandemia
WHERE `ÁREA GEOGRÁFICA` = 'Total'

"""

conn.execute(consulta)

In [34]:
consulta = """
CREATE TABLE info_proyeccion_mpios_v2
AS

WITH Tabla_Antes AS (

SELECT 
CASE WHEN LENGTH(CAST(DP AS STRING)) = 1 THEN CONCAT('0',CAST(DP AS STRING))
ELSE CAST(DP AS STRING) END AS c_digo_departamento,
CASE WHEN LENGTH(CAST(MPIO AS STRING)) = 4 THEN CONCAT('0',CAST(MPIO AS STRING))
ELSE CAST(MPIO AS STRING) END AS c_digo_municipio,
AÑO AS a_o,
Población AS poblacion_total
FROM informacion_antes_pandemia
WHERE `ÁREA GEOGRÁFICA` = 'Total'
)

, Tabla_Despues AS (

SELECT 
CASE WHEN LENGTH(CAST(DP AS STRING)) = 1 THEN CONCAT('0',CAST(DP AS STRING))
ELSE CAST(DP AS STRING) END AS c_digo_departamento,
CASE WHEN LENGTH(CAST(MPIO AS STRING)) = 4 THEN CONCAT('0',CAST(MPIO AS STRING))
ELSE CAST(MPIO AS STRING) END AS c_digo_municipio,
AÑO AS a_o,
Población AS poblacion_total
FROM informacion_despues_pandemia
WHERE `ÁREA GEOGRÁFICA` = 'Total'
)

SELECT * FROM Tabla_Antes
UNION ALL
SELECT * FROM Tabla_Despues
"""

conn.execute(consulta)

In [35]:
consulta2 = """
SELECT * FROM info_proyeccion_mpios
"""

info_proyecciones_dane = pd.read_sql_query(consulta2,conn)

In [36]:
info_proyecciones_dane.query("c_digo_departamento == '95'")

Empty DataFrame
Columns: [c_digo_departamento, c_digo_municipio, a_o, poblacion_total]
Index: []

In [37]:
(
    df_raw
    .assign(a_o = lambda x: x['a_o'].astype(int))
    .merge(info_proyecciones_dane.drop(columns = 'c_digo_departamento'), 
           on = ['c_digo_municipio','a_o'], how = 'left')
)

,a_o,c_digo_municipio,municipio,c_digo_departamento,c_digo_etc,etc,poblaci_n_5_16,tasa_matriculaci_n_5_16,cobertura_neta,cobertura_neta_transici_n,...,reprobaci_n_media,repitencia,repitencia_transici_n,repitencia_primaria,repitencia_secundaria,repitencia_media,tama_o_promedio_de_grupo,sedes_conectadas_a_internet,departamento,poblacion_total
0,2023,05004,Abriaquí,05,3758,Antioquia (ETC),503,62.62,62.62,44.19,...,2.04,9.52,0,10.46,13.76,2.04,NaN,NaN,Antioquia,2841.0
1,2023,95025,El Retorno,95,3830,Guaviare (ETC),4438,53.27,53.27,33.91,...,1.75,9.34,6.95,11.84,8.48,3.16,NaN,NaN,Guaviare,NaN
2,2023,95200,Miraflores,95,3830,Guaviare (ETC),2014,32.52,32.52,17.58,...,7.81,8.65,6.67,9.04,10.25,1.54,NaN,NaN,Guaviare,NaN
3,2023,97001,Mitú,97,3831,Vaupés (ETC),10986,59.57,59.57,42.76,...,4.6,16.18,7.75,21.04,13.84,7.18,NaN,NaN,Vaupés,NaN
4,2023,97161,Caruru,97,3831,Vaupés (ETC),1228,51.30,51.3,76.32,...,7.27,9.24,2.86,7.62,14.85,3.64,NaN,NaN,Vaupés,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14577,2011,05036,Angelópolis,05,3758,Antioquia (ETC),1707,78.85,78.9,56.2,...,7.32,0.71,0,0.7,1.08,0,19.57,100,Antioquia,5801.0
14578,2011,05034,Andes,05,3758,Antioquia (ETC),10244,84.45,84.5,65.1,...,2.69,5.41,0.73,5.53,6.9,4.11,24.43,93.44,Antioquia,42173.0
14579,2011,05031,Amalfi,05,3758,Antioquia (ETC),5552,97.71,97.7,61.7,...,0,NaN,0.83,NaN,9.93,4.47,20.01,53.45,Antioquia,24156.0
14580,2011,05030,Amagá,05,3758,Antioquia (ETC),6631,78.65,78.7,55.3,...,7.45,0.42,0,0.24,0.91,0,25.05,83.33,Antioquia,28354.0
14581,2011,05021,Alejandría,05,3758,Antioquia (ETC),702,118.52,118.5,82.7,...,8.04,0.6,0,0.96,0,0,32.14,81.25,Antioquia,4678.0

In [39]:
consulta3 = """
SELECT
CASE WHEN LENGTH(CAST(DP AS STRING)) = 1 THEN CONCAT('0',CAST(DP AS STRING))
ELSE CAST(DP AS STRING) END AS c_digo_departamento,
CASE WHEN LENGTH(CAST(MPIO AS STRING)) = 4 THEN CONCAT('0',CAST(MPIO AS STRING))
ELSE CAST(MPIO AS STRING) END AS c_digo_municipio,
AÑO AS a_o,
Población AS poblacion_total
FROM informacion_despues_pandemia
WHERE DP = 95 
AND `ÁREA GEOGRÁFICA` = 'Total'
"""

pd.read_sql_query(consulta3, conn)

    c_digo_departamento  c_digo_municipio   a_o  poblacion_total
0                    95             95001  2020            56294
1                    95             95001  2021            57717
2                    95             95001  2022            59555
3                    95             95001  2023            61403
4                    95             95001  2024            63208
..                  ...               ...   ...              ...
59                   95             95200  2031             9643
60                   95             95200  2032             9833
61                   95             95200  2033            10040
62                   95             95200  2034            10227
63                   95             95200  2035            10406

[64 rows x 4 columns]